apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: quote-canary
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: quote
status:
  loadBalancer: {}
